[package]
name = "lynthia-kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = "1.5"
ocl = "0.19"
half = "2.2"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
rand = "0.8"
ndarray-rand="0.15"
ndarray="0.15"


[dev-dependencies]
approx = "0.5"
