[package]
name = "lynthia-kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
ndarray = "0.15"
rayon = "1.5"
ocl = "0.19"
half = "2.2"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"


[dev-dependencies]
approx = "0.5"
